language: node_js
node_js:
  - "7"

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y lftp
  - rvm install 2.6
  - gem install bundler
  - npm install --global pug
  - openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in "./deploy_key.enc" -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - git config --global user.name "Travis-CI"
  - git config --global user.email "travis-ci@example.com"

script:
  - bundle install
  - bundle exec jekyll build
  - '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash ./deploy.sh'

after_script:
  - rm -rf _site
  - cat _config.yml | sed -e 's/baseurl: "/baseurl: "\/nagahara/' | sed -e 's/https:\/\/nagahara-lab.github.io/http:\/\/ids.osaka-u.ac.jp/' > _config.yml
  - bundle exec jekyll build
  - rm -rf _site/deploy*
  - '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash ./deploy.sh'
